back/backend_depr/controllers/GalleryController.php
<?php

namespace app\backend\controllers;

use app\models\Photo;
use app\models\search\Gallery as gallerySearch;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * GalleryController implements the CRUD actions for gallery model.
 */
class GalleryController extends Controller
{
    public function behaviors()
    {
        return [
//            'access' => [
//                'class' => AccessControl::className() ,
//                'rules' => [
//                    [
//                        'allow' => TRUE ,
//                        'roles' => [ '@' ] ,
//                    ] ,
//                ] ,
//            ] ,
//            'verbs' => [
            //                'class' => VerbFilter::className(),
            //                'actions' => [
            //                    'delete' => ['post','pjax'],
            //                ],
            //            ],
        ];
    }

    /**
     * Lists all gallery models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new gallerySearch;

        $dataProvider = $searchModel->search( Yii::$app->request->getQueryParams() );

        $dataProvider->pagination->pageSize = 24;
        $dataProvider->sort->defaultOrder = [ 'photoDate' => 'asc' ];

        return $this->render( 'index' , [
            'dataProvider' => $dataProvider ,
            'searchModel' => $searchModel ,
        ] );
    }

    /**
     * Displays a single gallery model.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView( $id )
    {
        return $this->render( 'view' , [
            'model' => $this->findModel( $id ) ,
        ] );
    }

    /**
     * Creates a new gallery model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Photo;

        if ( $model->load( Yii::$app->request->post() ) && $model->save() ) {
            return $this->redirect( [
                'view' ,
                'id' => $model->photoId
            ] );
        } else {
            return $this->render( 'create' , [
                'model' => $model ,
            ] );
        }
    }

    /**
     * Updates an existing gallery model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionUpdate( $id )
    {
        $model = $this->findModel( $id );

        if ( $model->load( Yii::$app->request->post() ) && $model->save() ) {
            return $this->redirect( [
                'view' ,
                'id' => $model->photoId
            ] );
        } else {
            return $this->render( 'update' , [
                'model' => $model ,
            ] );
        }
    }

    /**
     * Deletes an existing gallery model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionDelete( $id )
    {
        $this->findModel( $id )->delete();
        return $this->redirect( [ 'index' ] );
    }

    public function beforeAction( $action )
    {
        return parent::beforeAction( $action );
    }

    /**
     * Finds the gallery model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.

     *
*@param integer $id

     *
*@return Photo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel( $id )
    {
        if ( ( $model = Photo::findOne( $id ) ) !== NULL ) {
            return $model;
        } else {
            throw new NotFoundHttpException( 'The requested page does not exist.' );
        }
    }
}

back/backend_depr/views/gallery/_form.php
<?php

/**
 * @var yii\web\View           $this
 * @var app\models\Photo     $model
 * @var yii\widgets\ActiveForm $form
 */
?>

back/backend_depr/views/gallery/_item.php
<?php

/* @var app\models\Photo $model
 *
 */

use app\models\Photo;
use yii\helpers\Html;

?>
<?=
Html::a( Html::img( Photo::getImageLink( $model->photoPath , TRUE ) ) , Photo::getImageLink( $model->photoPath ) , [
    'class' => 'thumbnail' , 'rel' => 'fancybox' , 'data-pjax' => '0'
] ) ?>
<div class="gallery-action-bar">
    <?= Html::a( '' , '#' , [ 'class' => 'glyphicon glyphicon-file white' , 'data-role' => 'replace-button' ] ) ?>
    <?=
    Html::a( '' , [ 'gallery/delete' , 'id' => $model->photoId ] , [
        'data-pjax' => '0' , 'class' => 'glyphicon glyphicon-remove white' , 'data-role' => 'delete-button'
    ] ) ?>
</div>

back/backend_depr/views/gallery/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View              $this
 * @var app\models\search\Gallery $model
 * @var yii\widgets\ActiveForm    $form
 */
?>

<div class="gallery-search">

    <?php $form = ActiveForm::begin( [
        'action' => [ 'index' ] ,
        'method' => 'get' ,
    ] ); ?>

    <?= $form->field( $model , 'photoId' ) ?>

    <?= $form->field( $model , 'photoDate' ) ?>

    <?= $form->field( $model , 'photoPath' ) ?>

    <?= $form->field( $model , 'photoOriginal' ) ?>

    <div class="form-group">
        <?= Html::submitButton( 'Search' , [ 'class' => 'btn btn-primary' ] ) ?>
        <?= Html::resetButton( 'Reset' , [ 'class' => 'btn btn-default' ] ) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

back/backend_depr/views/gallery/index.php
<?php

use app\backend\components\widgets\Panel;
use newerton\fancybox\FancyBox;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;

/**
 * @var yii\web\View                $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\News      $searchModel
 */
$ajaxUploadLink = yii::$app->urlManager->createUrl( [ '/backend/ajax/upload' ] );

//        'js/jquery.ui.widget.js' ,
//        'js/jquery.iframe-transport.js' ,
//        'js/jquery.fileupload.js' ,
$this->registerJs( "var ajaxUploadLink = '$ajaxUploadLink'" , view::POS_HEAD );
$this->registerJs( "var pageSize = '{$dataProvider->pagination->pageSize}'" , view::POS_HEAD );
$this->registerAssetBundle( 'app\common\assets\packages\HandlebarsAsset' , View::POS_END );

$this->title = 'News';
$this->params[ 'breadcrumbs' ][ ] = $this->title;
?>


<?php Panel::begin( [
    'headerContent' => $this->title ,
    'containerOptions' => [ 'class' => 'container' ]
] ) ?>

<div class="col-lg-12">

    <?php $form = ActiveForm::Begin( [ 'options' => [ 'enctype' => "multipart/form-data" ] ] ) ?>
    <div id="errors" class="alert"></div>

    <?=
    Html::fileInput( 'upload' , '' , [
        'style' => 'display:none' , 'id' => 'upload-form' , 'multiple' => TRUE
    ] ) ?>
    <?= Html::hiddenInput( 'replace-id' , '' , [ 'style' => 'display:none' , 'id' => 'replace-id' ] ) ?>
    <?php ActiveForm::End() ?>
    <?= Html::a( 'Загрузить фото!' , '#' , [ 'class' => 'btn btn-success' , 'id' => 'upload-button' ] ) ?>
    <hr>

</div>
<?=
ListView::widget( [
    'id' => 'list-view' ,
    'dataProvider' => $dataProvider ,

    'itemView' => '_item' ,
    'itemOptions' => [ 'data-role' => 'item' , 'class' => 'col-xs-2 m-b-xs' ] ,

    'layout' => '{items}</div><div class="col-lg-12"><hr>{pager}' ,
    'pager' => [ 'hideOnSinglePage' => TRUE ]
] ) ?>
<?php Panel::end() ?>


<?=
FancyBox::widget( [
    'target' => 'a[rel=fancybox]' ,
    'config' => [
        'maxWidth' => '100%' ,
        'maxHeight' => '100%' ,
        'padding' => FALSE ,
        'closeBtn' => TRUE ,
        'openOpacity' => TRUE ,
    ]
] );
?>
<script id="item" type="text/x-handlebars-template">

    <div class="col-xs-2 m-b-xs" data-role="item" data-key="{{photoId}}">
        <a class="thumbnail" href="/images/pics/{{photoPath}}" rel="fancybox" data-pjax="0"><img src='/images/thumbs/{{photoPath}}' alt=""></a>

        <div class="gallery-action-bar">
            <a class="glyphicon glyphicon-file white" href="#" data-role="replace-button"></a>
            <a class="glyphicon glyphicon-remove white" href='/backend/gallery/delete?id={{photoId}}' data-pjax="0" data-role="delete-button"></a>
        </div>

    </div>
</script>